### PR TITLE
Fixes Issue #690 ticks should not overwrite min/max settings

### LINKED ISSUE #690: ticks should not overwrite min/max settings
## Problem:
Currently if you specify `ticks` the `min/max` settings get overwritten by the minimum and maximum tick value.

This causes a couple of problems:
1. Unexpected results if you have only one tick (at which point `min==max==ticks[0]`).
2. Prevents usage scenarios where ticks should not be at the minima/maxima of the slider.

https://jsfiddle.net/nonplus/ws68hrmf/

## Expected behavior:
1. If min configured, use specified min, regardless of ticks
1. If max configured, use specified max, regardless of ticks
1. If no min configured and ticks configured, use smallest tick as min (existing behavior)
1. If no max configured and ticks configured, use largest tick as max  (existing behavior)
1. If no min and no ticks configured, default min to 0  (existing behavior)
1. If no max and no ticks configured, default max to 10  (existing behavior)

I can provide a PR.

### PR DESCRIPTION
**Pull request by jespirit**
Fixes #690 

Pull Requests
=============
Please accompany all pull requests with the following (where appropriate):

- [x] unit tests (we use [Jasmine 2.x.x](https://jasmine.github.io/2.2/introduction))
- [ ] JSFiddle (or an equivalent such as CodePen, Plunker, etc) or screenshot/GIF with new feature or bug-fix
- [x] Link to original Github issue (if this is a bug-fix)
- [ ] Passes CI-server checks (runs automated tests, JS source-code linting, etc..). To run these on your local machine, type `grunt test` in your Terminal within the bootstrap-slider repository directory

### CODE REVIEW

File: src/js/bootstrap-slider.js [hunk 1]
```diff
@@ -372,6 +372,9 @@ const windowIsDefined = (typeof window === "object");
 			options = options ? options : {};
 			var optionTypes = Object.keys(this.defaultOptions);
 
+			var isMinSet = 'min' in options;
```
Comment (rovolution) [inline src/js/bootstrap-slider.js]: could you refactor this to use `hasOwnProperty` instead of the `in` keyword?  `hasOwnProperty` checks the object only versus traversing the prototype chain

Comment (rovolution) [reply src/js/bootstrap-slider.js]: also, refactor these `var`s to be `const`s (since their values do not change)
