### PR TITLE
Fixes Issue #876: Values for range slider are not the same

### LINKED ISSUE #876: Values for range slider are not the same for 'slideStart' and 'change' events
When using the keyboard to move handles for a range slider at the min or max ends, the values for the `slideStart` and `change` events are different.

1. Open console.
2. Focus the keyboard on either handle and key to the left or right.

'slideStart' gives [-101, 0] while 'change' gives [-100, 0]

https://jsfiddle.net/jexrpwym/

Issues
=============
**NOTE:** Before filing a new issue, please search through the open issues list and check to see if an existing issue already exists that describes your problem. If so, leave a comment within that issue with the checklist items described below.

Please make sure you include the following in your issue report where appropriate:

- [x] JSFiddle (or an equivalent such as CodePen, Plunker, etc) with the an example demonstrating the bug
- [x] Instructions to replicate the bug in the Fiddle

### PR DESCRIPTION
**Pull request by jespirit**
Fixes #876 

I've added unit tests

### CODE REVIEW

File: test/specs/KeyboardSupportSpec.js [hunk 1]
```diff
@@ -489,4 +489,68 @@ describe("Keyboard Support Tests", function() {
...
+    afterEach(function() {
+      if (mySlider) {
+        if (mySlider instanceof Slider) { mySlider.destroy(); }
+        mySlider = null;
+      }
+    });
+
+    it("Should not go below minimum at 'slideStart'", function(done) {
+      options.value = [-100, 0];
+      mySlider = new Slider($('#testSlider1')[0], options);
```
Comment (rovolution) [inline test/specs/KeyboardSupportSpec.js]: nice tests!
